app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /doc.json
  methods: GET
  defaults:
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    path: /doc
    permanent: true