services:
  _instanceof:
    App\Api\Application\Command\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

  App\Api\Application\Command\CreateProductCommandHandler:
    tags: [{ name: messenger.message_handler, bus: command.bus }]
    arguments:
      $productFactory: '@App\Api\Domain\Product\ProductFactoryInterface'
      $priceFactory: '@App\Api\Domain\Product\PriceFactoryInterface'
      $productRepository: '@App\Api\Domain\Product\ProductRepositoryInterface'
      $priceRepository: '@App\Api\Domain\Product\PriceRepositoryInterface'
      $dispatcher: '@debug.event_dispatcher'

  App\Api\Application\Serializer\AppSerializer:
    public: false

  App\Api\Application\Serializer\AppSerializerInterface:
    alias: App\Api\Application\Serializer\AppSerializer
    public: true

  App\Api\Application\EventSubscriber\ProductSubscriber:
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      $mailer: '@mailer.mailer'